### PR TITLE
Add fisheye camera calibration

### PR DESCRIPTION
**Pull request by decamargo10**
Hello,
first of all, I want to thank you for your great work! As there is no fisheye calibration included yet (#16), here is a way to include fisheye cameras using the arg --isFisheye True. I successfully calibrated a set of 3 fisheye cameras and visualized the results.
Basically, I just copied the camera class and replaced the OpenCV calls. However, I encountered an issue where empty error arrays were handed into calibration/error_stats() which caused errors (this does not only happen to me when using fisheye calibration but also the regular one). I don't know if my 'fix' for this is ideal, it seems to work though, and as far as I understand, it does not influence the results in any way.
Please let me know about things you want to have changed.

### CODE REVIEW

**Comment by oliver-batchelor** [comment]
Thanks! Very nice - I'll have to have a little think how to choose the camera model properly, but this is a great additon!

Is there a chance you could share the images for the fisheye calibration you did? I need to publish some test images for the library and some fisheye ones would be great along side others.

**Comment by decamargo10** [comment]
Sure, I can upload them somewhere. Just let me know the best way to provide them to you (~730mb of images).

**Comment by oliver-batchelor** [comment]
Could you copy them to a google drive? If you send me an email at oliver.batchelor@cantebrury.ac.nz  I can add you (as it seems there's no way to share it privately here and it would be better not to be publicly writable!). 

Thanks,
Oliver

**Comment by steczol** [comment]
Thank you for your work. Is there any possibility to estimate the extrinsics between a fisheye camera (main camera) and a regular camera? As far as I understand the arguments to `multical calibrate` you can switch between no fisheye and all fisheye, right?

**Comment by oliver-batchelor** [comment]
Yes, that's right.

In principle, it's not an issue. It just needs some way to provide the
configuration to set it up that way.  I imagine something like a config
file (yaml/json etc.) where you describe the cameras/camera model setup
ahead of time would do the job for a general solution.

However, you can use the code as a python library to do it as a once-off
and change the relevant parts where it is setting up the camera models.

Cheers,
Oliver

**Pull request merged**
